# Generated by Django 4.2 on 2026-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
